#!/usr/bin/env python3
"""Create and stream-feed a one-shard OpenSearch or Elasticsearch index."""

import argparse
import json
import threading
import time

from adapters import make_adapter
from http_sync import request_bytes, request_json
from schema import BODY_FIELD, ID_FIELD, REST_BODY_MAPPING, REST_ID_MAPPING
from topologies import TOPOLOGIES, assert_topology, resolve_topology
from topology_probe import index_topology

MAPPINGS = {
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0,
        "refresh_interval": "-1"
    },
    "mappings": {
        # strict: an unmapped corpus field fails the feed loudly instead of
        # dynamic-mapping as text and silently breaking term filters/aggs.
        "dynamic": "strict",
        "_source": {"enabled": True},
        "properties": {
            # The engine-generated _id keeps ingestion on the append-only fast
            # path. Corpus identity is an ordinary keyword: postings serve
            # exact lookup and doc values serve hit projection.
            ID_FIELD: REST_ID_MAPPING,
            BODY_FIELD: REST_BODY_MAPPING,
            "sort_i": {"type": "long"},
            "cat_s": {"type": "keyword"},
            "cat100_s": {"type": "keyword"},
            "cat1k_s": {"type": "keyword"},
            "cat10k_s": {"type": "keyword"},
            "cat100k_s": {"type": "keyword"},
            "cat1m_s": {"type": "keyword"},
            "cat5m_s": {"type": "keyword"},
            "catu2m_s": {"type": "keyword"},
            "catid_s": {"type": "keyword"},
            "sel99_s": {"type": "keyword"},
            "sel90_s": {"type": "keyword"},
            "sel50_s": {"type": "keyword"},
            "sel10_s": {"type": "keyword"},
            "sel1_s": {"type": "keyword"},
            "sel01_s": {"type": "keyword"},
            "sel001_s": {"type": "keyword"},
            "date_dt": {"type": "date"},
            "price_i": {"type": "integer"}
        }
    }
}


def bulk_chunks_from_stream(source, index, docs_per_chunk, document_limit=None,
                            context="corpus"):
    """Splice raw corpus records into _bulk bodies.

    The corpus is already NDJSON, one document per line, so a bulk body is the
    action line plus the record verbatim - no parse, no re-serialization. That
    is load-bearing, not tidiness: chunk construction runs under send_chunks'
    lock, so it is one Python thread for the whole feed however many clients
    are asked for, and json.loads + json.dumps per document capped it at
    ~75k docs/s - below what Elasticsearch itself reaches at 16 clients, which
    made every measurement above that a measurement of this feeder.

    The id check that cost the parse now samples the first record of the range
    instead of every one: it exists to catch a wrong or malformed corpus, and
    the corpus is content-hashed and generated by scripts/prepare-corpus.sh.
    Omitting _id is intentional: ES/OS mark the operation as an auto-ID append
    and can skip the overwrite/version lookup.
    """
    action = json.dumps({"index": {"_index": index}},
                        separators=(",", ":")).encode() + b"\n"
    batch = bytearray()
    batch_docs = 0
    total_docs = 0
    checked = False
    while document_limit is None or total_docs < document_limit:
        line = source.readline()
        if not line:
            if document_limit is not None:
                raise RuntimeError(
                    f"{context} expected {document_limit} documents, source ended "
                    f"after {total_docs}")
            break
        if not line.strip():
            continue
        if not checked:
            checked = True
            probe = json.loads(line)
            if not isinstance(probe.get(ID_FIELD), str) or not probe[ID_FIELD]:
                raise ValueError("corpus document has no non-empty string id")
        batch += action
        batch += line if line.endswith(b"\n") else line + b"\n"
        batch_docs += 1
        total_docs += 1
        if batch_docs >= docs_per_chunk:
            yield bytes(batch), batch_docs
            batch.clear()
            batch_docs = 0
    if batch:
        yield bytes(batch), batch_docs


def bulk_chunks(path, index, docs_per_chunk):
    with open(path, "rb") as source:
        yield from bulk_chunks_from_stream(source, index, docs_per_chunk)


def send_chunks(chunks, clients, send_bulk, flush_every=0, flush=None):
    """Drain one bounded chunk iterator over parallel bulk connections."""
    lock = threading.Lock()
    state = {"batches": 0, "documents": 0, "took": 0, "error": None}

    def worker():
        sent_since_flush = 0
        while True:
            with lock:
                if state["error"]:
                    return
                try:
                    item = next(chunks)
                except StopIteration:
                    item = None
                except Exception as error:
                    state["error"] = error
                    return
            if item is None:
                if flush_every and sent_since_flush:
                    try:
                        flush()
                    except Exception as error:
                        with lock:
                            state["error"] = state["error"] or error
                return
            chunk, ndocs = item
            try:
                took = send_bulk(chunk)
            except Exception as error:
                with lock:
                    state["error"] = state["error"] or error
                return
            with lock:
                state["batches"] += 1
                state["documents"] += ndocs
                state["took"] += took
            if flush_every:
                # Deterministic segment boundaries require one client, so the
                # counter and flush call have no cross-worker race.
                sent_since_flush += ndocs
                if sent_since_flush >= flush_every:
                    try:
                        flush()
                    except Exception as error:
                        with lock:
                            state["error"] = state["error"] or error
                        return
                    sent_since_flush -= flush_every

    if clients > 1:
        threads = [threading.Thread(target=worker) for _ in range(clients)]
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()
    else:
        worker()
    if state["error"]:
        raise state["error"]
    return state


def feed_topology(args, topology, send_bulk):
    """Feed exact declared ranges and prove each bounded-force-merge result."""
    adapter = make_adapter(args.engine, args.index)
    boundaries = []
    totals = {"batches": 0, "documents": 0, "took": 0}
    with open(args.corpus, "rb") as source:
        for range_index, expected_docs in enumerate(topology.segment_docs, 1):
            range_started = time.monotonic()
            chunks = bulk_chunks_from_stream(
                source, args.index, args.batch_docs, expected_docs,
                f"topology {topology.name} range {range_index}")
            state = send_chunks(iter(chunks), args.clients, send_bulk)
            if state["documents"] != expected_docs:
                raise RuntimeError(
                    f"topology {topology.name} range {range_index} sent "
                    f"{state['documents']} documents; expected {expected_docs}")
            for name in totals:
                totals[name] += state[name]

            # Publish and durably close the range before asking Lucene's
            # explicit merge path to reduce the whole index to the number of
            # declared tiers fed so far.
            request_json(args.host, args.port, "POST", f"/{args.index}/_refresh",
                         timeout=600)
            request_json(args.host, args.port, "POST",
                         f"/{args.index}/_flush?wait_if_ongoing=true", timeout=600)
            merged = request_json(
                args.host, args.port, "POST",
                f"/{args.index}/_forcemerge?max_num_segments={range_index}&flush=true",
                timeout=3600)
            if merged.get("_shards", {}).get("failed", 0):
                raise RuntimeError(
                    f"topology {topology.name} range {range_index} force merge failed: "
                    f"{merged}")
            # A force merge commits its output but does not promise to reopen
            # the search reader. _segments must inspect the reader that the
            # benchmark will actually serve.
            request_json(args.host, args.port, "POST", f"/{args.index}/_refresh",
                         timeout=600)
            observed = index_topology(
                adapter, args.host, args.port, timeout=120)
            declared = topology.after_ranges(range_index)
            assert_topology(declared, observed)
            boundaries.append({
                "range": range_index,
                "range_documents": expected_docs,
                "total_documents": declared.documents,
                "force_merge_max_segments": range_index,
                "elapsed_s": round(time.monotonic() - range_started, 3),
                "observed": observed,
            })

        if next((line for line in source if line.strip()), None) is not None:
            raise RuntimeError(
                f"topology {topology.name} consumes {topology.documents} documents "
                "but the corpus contains more")
    if totals["documents"] != topology.documents:
        raise RuntimeError(
            f"topology {topology.name} sent {totals['documents']} documents; "
            f"expected {topology.documents}")
    return totals, boundaries


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("engine", choices=("opensearch", "elasticsearch"))
    parser.add_argument("corpus")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int)
    parser.add_argument("--index", default="searchbench")
    parser.add_argument("--batch-docs", type=int, default=1000)
    parser.add_argument("--clients", type=int, default=16,
                        help="concurrent _bulk connections (ingest-parallelism dimension)")
    parser.add_argument("--variant", choices=("full", "facet"), default="full")
    parser.add_argument("--source", action=argparse.BooleanOptionalAction, default=True,
                        help="store _source (default). --no-source drops the stored JSON "
                             "copy of every document, which is what makes an ES/OS index "
                             "size-comparable to luxir (luxir never stores whole source "
                             "documents, and does not put strings/ints in its stored-fields "
                             "region by default). All tasks, including GET_*, retrieve "
                             "projected scalar fields from doc values.")
    parser.add_argument("--flush-every", type=int, default=0,
                        help="flush at every N-doc boundary (segment-topology "
                             "control; requires --clients 1)")
    parser.add_argument("--topology", choices=tuple(TOPOLOGIES),
                        help="named exact document-range topology")
    parser.add_argument("--settings", default=None,
                        help="JSON object of index settings merged over the "
                             "campaign posture (ingest-tuning experiments)")
    parser.add_argument("--reset", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--refresh", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--optimize", action="store_true")
    args = parser.parse_args()
    if args.topology and args.flush_every:
        parser.error("--topology and --flush-every are mutually exclusive")
    if args.topology and not args.reset:
        parser.error("--topology requires --reset")
    if args.topology and not args.refresh:
        parser.error("--topology requires --refresh")
    if args.topology and args.optimize:
        parser.error("--topology cannot be combined with --optimize")
    port = args.port or {"opensearch": 9201, "elasticsearch": 9202}[args.engine]
    args.port = port
    topology = resolve_topology(args.topology) if args.topology else None
    headers = None
    if args.reset:
        try:
            request_json(args.host, port, "DELETE", f"/{args.index}", headers=headers)
        except RuntimeError as error:
            if "HTTP 404" not in str(error):
                raise
    mappings = json.loads(json.dumps(MAPPINGS))
    if not args.source:
        # _source is the stored JSON copy of the whole document and can
        # dominate index size. Luxir has no equivalent - it never stores whole
        # source documents - so leaving it on makes an index-size comparison
        # measure a feature luxir does not have. GET_* and top-doc tasks use
        # doc values, so every benchmark shape remains available.
        mappings["mappings"]["_source"] = {"enabled": False}
    if args.variant == "facet":
        # Facet-variant corpus carries no text; a mapped-but-absent text field
        # would be free, but the mapping should describe the index honestly.
        del mappings["mappings"]["properties"][BODY_FIELD]
    if args.engine == "opensearch":
        # Accurate-to-accurate default posture (bench mode table): OS 3.x
        # concurrent segment search makes single-shard terms aggs APPROXIMATE
        # (slice-level shard_size truncation; measured error 19k on the 8-seg
        # grid shape). Baked at creation so every consumer gets exact counts;
        # the as-shipped concurrent posture is an explicit _settings A/B.
        mappings["settings"]["search.concurrent_segment_search.mode"] = "none"
    if args.flush_every or topology:
        # Keep translog auto-flushes out of explicit range boundaries. Lucene
        # may still RAM-flush within a range; its pieces are consolidated by
        # that range's bounded force merge.
        mappings["settings"]["translog.flush_threshold_size"] = "8gb"
        # Keep background TieredMergePolicy work from racing the explicit
        # construction. A named topology KEEPS this guard: the declared shape
        # has to survive a node restart, and the default budget does not leave
        # it alone. Nine segments per tier is inside the default
        # segments_per_tier of 10, but floor_segment (2 MiB) treats every
        # segment below the floor as floor-sized, so the 100-document and
        # 1,000-document tiers count as one oversized tier and are merged on
        # the reopen that follows construction: tiered-45 was observed
        # collapsing to 28 segments as soon as the serving process restarted.
        # An index measured read-only never runs a merge anyway, so retaining
        # the guard costs the campaign nothing and is recorded in the feed
        # record below.
        mappings["settings"]["merge.policy.segments_per_tier"] = (
            100 if topology else 48)
    if args.settings:
        # Last word, so an experiment can override any posture set above.
        mappings["settings"].update(json.loads(args.settings))
    request_json(args.host, port, "PUT", f"/{args.index}", mappings, headers=headers)
    started = time.monotonic()
    def send_bulk(chunk):
        response = request_bytes(args.host, port, "POST", "/_bulk", chunk,
                                 "application/x-ndjson", timeout=300, headers=headers)
        if response.get("errors"):
            failures = [item for item in response.get("items", [])
                        if item.get("index", {}).get("status", 200) >= 300]
            raise RuntimeError(f"bulk failures: {failures[:3]}")
        return response.get("took", 0)

    if args.flush_every and args.clients > 1:
        raise SystemExit("--flush-every requires --clients 1 (deterministic boundaries)")
    boundaries = None
    try:
        if topology:
            state, boundaries = feed_topology(args, topology, send_bulk)
        else:
            chunks = bulk_chunks(args.corpus, args.index, args.batch_docs)
            state = send_chunks(
                iter(chunks), args.clients, send_bulk,
                flush_every=args.flush_every,
                flush=(lambda: request_json(
                    args.host, port, "POST", f"/{args.index}/_flush",
                    headers=headers)))
    finally:
        restore = {"refresh_interval": "1s"}
        if args.flush_every or topology:
            restore["translog.flush_threshold_size"] = None
        request_json(args.host, port, "PUT", f"/{args.index}/_settings",
                     {"index": restore})
    if args.refresh:
        request_json(args.host, port, "POST", f"/{args.index}/_refresh", headers=headers)
    if args.optimize:
        request_json(args.host, port, "POST", f"/{args.index}/_forcemerge?max_num_segments=1",
                     headers=headers)
        if args.refresh:
            request_json(args.host, port, "POST", f"/{args.index}/_refresh", headers=headers)
    final_topology = None
    if topology:
        final_topology = index_topology(
            make_adapter(args.engine, args.index), args.host, port, timeout=120)
        assert_topology(topology, final_topology)
    elapsed = time.monotonic() - started
    count = request_json(args.host, port, "GET", f"/{args.index}/_count", headers=headers)
    print(json.dumps({"bulk_batches": state["batches"],
                      "bulk_took_ms": state["took"],
                      "clients": args.clients,
                      "batch_docs": args.batch_docs,
                      "index_settings": mappings["settings"],
                      "internal_id": "auto_generated",
                      "topology": None if topology is None else {
                          "name": topology.name,
                          "segment_docs": list(topology.segment_docs),
                          "expected_segments": topology.segment_count,
                          "documents": topology.documents,
                          "boundaries": boundaries,
                          "final_observed": final_topology,
                          # Kept on the index so the declared shape survives a
                          # restart; see the construction settings above.
                          "retained_settings": {
                              "merge.policy.segments_per_tier":
                                  mappings["settings"]["merge.policy.segments_per_tier"],
                          },
                      },
                      "elapsed_s": round(elapsed, 3),
                      "docs_per_s": round(count.get("count", 0) / elapsed, 1) if elapsed else None,
                      "count": count.get("count")}, indent=2))


if __name__ == "__main__":
    main()
